export const dummyData = [
  {
    category: "rings",
    title: "RINGS",
    description: "Hundreds of styles for men and women.",
    buttonText: "SHOP RINGS",
    imageSrc: "/src/assets/images/homebanner-rings.avif",
    data: [
      {
        id: 1,
        gender: "Male",
        image: "/src/assets/images/ring.jfif",
        desc: "Men's Classic Ring",
        price: "$150",
      },
      {
        id: 2,
        gender: "Female",
        image: "/src/assets/images/ring.jfif",
        desc: "Women's Elegant Ring",
        price: "$250",
      },
      {
        id: 3,
        gender: "Female",
        image: "/src/assets/images/ring.jfif",
        desc: "Women's Statement Ring",
        price: "$180",
      },
      {
        id: 4,
        gender: "Male",
        image: "/src/assets/images/ring.jfif",
        desc: "Men's Bold Ring",
        price: "$220",
      },
      {
        id: 5,
        gender: "Female",
        image: "/src/assets/images/ring.jfif",
        desc: "Women's Statement Ring",
        price: "$180",
      },
    ],
  },
  {
    category: "necklaces",
    title: "NECKLACES",
    description: "From timeless traditions to bold new styles.",
    buttonText: "SHOP NECKLACES",
    imageSrc: "/src/assets/images/homebanner-necklaces.avif",
    data: [
      {
        id: 1,
        gender: "Female",
        image: "/src/assets/images/homebanner-necklaces.avif",
        desc: "Timeless Pearl Necklace",
        price: "$300",
      },
      {
        id: 2,
        gender: "Female",
        image: "/src/assets/images/homebanner-necklaces.avif",
        desc: "Gold Chain Necklace",
        price: "$450",
      },
      {
        id: 3,
        gender: "Male",
        image: "/src/assets/images/homebanner-necklaces.avif",
        desc: "Men's Silver Chain",
        price: "$200",
      },
      {
        id: 4,
        gender: "Female",
        image: "/src/assets/images/homebanner-necklaces.avif",
        desc: "Bold Statement Necklace",
        price: "$500",
      },
    ],
  },
  {
    category: "watches",
    title: "WATCHES",
    description: "Choose from hundreds of watches for men and women!",
    buttonText: "SHOP WATCHES",
    imageSrc: "/src/assets/images/homebanner-watches.avif",
    data: [
      {
        id: 1,
        gender: "Male",
        image: "/src/assets/images/watch.jpg",
        desc: "Men's Classic Watch",
        price: "$250",
      },
      {
        id: 2,
        gender: "Female",
        image: "/src/assets/images/watch.jpg",
        desc: "Women's Elegant Watch",
        price: "$300",
      },
      {
        id: 3,
        gender: "Male",
        image: "/src/assets/images/watch.jpg",
        desc: "Men's Sports Watch",
        price: "$200",
      },
      {
        id: 4,
        gender: "Female",
        image: "/src/assets/images/watch.jpg",
        desc: "Women's Fashion Watch",
        price: "$400",
      },
    ],
  },
  {
    category: "bracelets",
    title: "BRACELETS",
    description:
      "Start with one and explore wearing multiple on one wrist for a unique combination.",
    buttonText: "SHOP BRACELETS",
    imageSrc: "/src/assets/images/homebanner-bracelets.avif",
    data: [
      {
        id: 1,
        gender: "Female",
        image: "/src/assets/images/homebanner-bracelets.avif",
        desc: "Classic Gold Bracelet",
        price: "$120",
      },
      {
        id: 2,
        gender: "Female",
        image: "/src/assets/images/homebanner-bracelets.avif",
        desc: "Silver Charm Bracelet",
        price: "$150",
      },
      {
        id: 3,
        gender: "Female",
        image: "/src/assets/images/homebanner-bracelets.avif",
        desc: "Layered Leather Bracelet",
        price: "$80",
      },
      {
        id: 4,
        gender: "Female",
        image: "/src/assets/images/homebanner-bracelets.avif",
        desc: "Diamond Accent Bracelet",
        price: "$300",
      },
    ],
  },
  {
    category: "pendants",
    title: "PENDANTS",
    description: "Add a touch of sparkle with our natural diamond pendants.",
    buttonText: "SHOP PENDANTS",
    imageSrc: "/src/assets/images/homebanner-pendants.avif",
    data: [
      {
        id: 1,
        gender: "Female",
        image: "/src/assets/images/homebanner-pendants.avif",
        desc: "Diamond Heart Pendant",
        price: "$500",
      },
      {
        id: 2,
        gender: "Female",
        image: "/src/assets/images/homebanner-pendants.avif",
        desc: "Gold Infinity Pendant",
        price: "$350",
      },
      {
        id: 3,
        gender: "Female",
        image: "/src/assets/images/homebanner-pendants.avif",
        desc: "Sapphire Teardrop Pendant",
        price: "$450",
      },
      {
        id: 4,
        gender: "Female",
        image: "/src/assets/images/homebanner-pendants.avif",
        desc: "Diamond Circle Pendant",
        price: "$600",
      },
    ],
  },
  {
    category: "gold-chains",
    title: "GOLDCHAINS",
    description:
      "Welcome to our collection of fine 14k solid gold chains, where luxury meets affordability. Each chain embodies superior quality and durability, ensuring a lifetime of beauty. Explore our selection of classic and statement-making designs at competitive prices, redefining luxury for the most deserving customer.",
    buttonText: "SHOP GOLD CHAINS",
    imageSrc: "/src/assets/images/homebanner-gold_chains.avif",
    data: [
      {
        id: 1,
        gender: "Male",
        image: "/src/assets/images/homebanner-gold_chains.avif",
        desc: "Classic Curb Chain",
        price: "$700",
      },
      {
        id: 2,
        gender: "Male",
        image: "/src/assets/images/homebanner-gold_chains.avif",
        desc: "14k Gold Rope Chain",
        price: "$650",
      },
      {
        id: 3,
        gender: "Male",
        image: "/src/assets/images/homebanner-gold_chains.avif",
        desc: "Box Link Chain",
        price: "$800",
      },
      {
        id: 4,
        gender: "Male",
        image: "/src/assets/images/homebanner-gold_chains.avif",
        desc: "Figaro Chain",
        price: "$750",
      },
    ],
  },
];
